//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlycoffe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string UserName { get; set; }
        public string DisplayName { get; set; }
        public string PassWord { get; set; }
        public int Type { get; set; }
        public string genner { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public byte[] avatar { get; set; }
    }
}
