//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlycoffe
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongKeBill
    {
        public int id { get; set; }
        public Nullable<System.DateTime> DateCheckOut { get; set; }
        public Nullable<double> tong { get; set; }
    }
}
